export const SIGN_IN_API = 'SIGN_IN_API'
export const THEO_DOI_PROJECT_CATEGORY_API = "THEO_DOI_PROJECT_CATEGORY_API"
export const THEO_DOI_CREATE_PROJECT_API = "THEO_DOI_CREATE_PROJECT_API"
export const THEO_DOI_GET_ALL_PROJECT_API = "THEO_DOI_GET_ALL_PROJECT_API"
export const THEO_DOI_DELETE_PROJECT_API = "THEO_DOI_DELETE_PROJECT_API"
export const THEO_DOI_UPDATE_PROJECT_API = "THEO_DOI_UPDATE_PROJECT_API"